

const allProducts = {
    lipBalmParent : "Lip Care",
    specialNeeds: "Special needs",
    moisturizingCreams:"Moisturizing cream",
    faceCare:"Face Care",
    antiageing:"Anti-ageing cream",
    lipbalm:"Lip Balm",
    lipScrubs:"Lip Scrubs",
    oilsAndSerums:"Oils and Serums",
    nightOil:"Night Oil",
    hairOil: "Hair Oil",
    faceSerum:"Skin brightening face serum",
    darkCirclesRemoval: "Under eye serum for dark circles",
    soaps: "Soaping bars",
    hydrosols:"Rose Hydrosol and Water",
    bodyScrub:"Body Scrubbers",
    footScrub:"Foot Scrubbers",
    normalSoaps: "Aromatic Soaps",
    scrubbers:"Scrubbers",
    footCare: "Foot care",
    bodyButter:"Body Butter",
    oils:"Oils",
    serums:"Serums",
    hairCare:"Hair Care",
    kidsFriendly:"Kids cream",
    sensitiveSkin:"Cream for sensitive Skin",
    roseHydrosol: "Rose Mist",
    roseWater:"Rose Arka",
    footHealer:"Foot Healer",
    kidSoap:"Kids friendly Soap",
    suitableFor:"Suitable for",
    quantity:"Quantity",
    ingredients:"Ingredients",
    price:"Cost",
    delivery:"Possible delivery within",
    availableinFlavours:"Available in flavours",
    howToUse:"How to use",
    precaution:"Precaution"
}

export default allProducts